### ISSUE TITLE
Unable to specify a city that consists of multiple words 

### ISSUE THREAD

**Issue by lpleva** [burgamacha/CVS-covid-vaccine-checker#10]
I am unable to get a response for cities that contain multiple words. For example, "Saint Petersburg" and "Clearwater Beach" in Florida. I confirmed these are in the JSON response on CVS' website. 

If I run the command `vaccine.py --state FL --cities Saint Petersburg`, the output just includes the most recent timestamp when the availability was checked - it doesn't list the city and the status. 

I also tried `vaccine.py --state FL --cities Saint%20Petersburg`, with no success. 

I don't have an issue running the script with cities that consist of a single word (e.g., Largo).

**Comment by lpleva** [comment]
Nevermind - I was able to get it to work by putting double quotes around these cities. 

`vaccine.py --state FL --cities "Saint Petersburg"`

**Comment by ctwardy** [comment]
Also I just created a pull request for accepting a `--cityfile` where cities are listed one per line.
